services:
  web:
    build: .
    container_name: legado-ivo-pitz
    volumes:
      - .:/Legado-Ivo-Pitz:rw,cached
    ports:
      - "8000:8000"
    env_file:
      - ./dotenv_files/.env
    command: >
      sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    #   POSTGRES_DB: ${POSTGRES_DB}
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_HOST: ${POSTGRES_HOST}
    #   POSTGRES_PORT: ${POSTGRES_PORT}
    # depends_on:
    #   - psql # Apenas necessário se for usado localmente (comentado abaixo para Railway)
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
  # Configuração do banco de dados local (comentada para uso no Railway)
  psql:
    container_name: postgres
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
    ports:
      - "5433:5432" # Expondo no host a porta 5433 para desenvolvimento local
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
