version: '3.9'

services:
  mysql_FamiliaPitz:
    container_name: mysql_FamiliaPitz
    image: mysql:8
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql_FamiliaPitz:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: America/Sao_Paulo

  web:
    image: python:3.10-slim
    container_name: legadoivopitz-web
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y gcc libmariadb-dev pkg-config &&
      pip install --no-cache-dir -r requirements.txt &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - mysql_FamiliaPitz
    environment:
      - DATABASE_HOST=mysql_FamiliaPitz
      - DATABASE_PORT=3306
      - DATABASE_NAME=${MYSQL_DATABASE}
      - DATABASE_USER=${MYSQL_USER}
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - PYTHONUNBUFFERED=1
